export const MONKEY_TRACK_FRAMES = 180
// const MONKEY_PASS_SEE_FRAMES_COUNT = 33
export const MONKEY_TRACK_FIRST_SEGMENT_ON_INPUT = 18
export const MONKEY_TRACK_LAST_SEGMENT_ON_INPUT = 160

export const MONKEY_PASS_SEE_FRAMES = 33
export const MONKEY_PASS_SEE_FIRST_SEGMENT = 0
export const MONKEY_PASS_SEE_LAST_SEGMENT = 15
