import '../subscribers/account'
import '../subscribers/chats'
import '../subscribers/messages'
import './api/account'
import './api/auth'
import './api/chats'
import './api/contacts'
import './api/folders'
import './api/langPack'
import './api/media'
import './api/messages'
import './api/search'
import './api/users'

/* Ui */
import './ui/chats'
import './ui/diff'
import './ui/init'
import './ui/search'
import './ui/settings'
import './ui/users'
